In [56]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_predict
from sklearn.preprocessing import MinMaxScaler

In [3]:
X_train = np.array([[1,1,1],[1,0,1],[1,0,0],[1,0,0],[1,1,1],[0,1,1],[0,0,0],[1,0,1],[0,1,0],[1,0,0]])
y_train = np.array([1,1,0,0,1,0,0,1,1,0])

In [58]:
clf = DecisionTreeClassifier(random_state=0)
iris = load_iris()
scaler = MinMaxScaler()
X = iris.data
scaler.fit(X)
X = scaler.transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, iris.target, test_size=0.33, random_state=42)
cross_val_score(clf, X_train, y_train, cv=10)

array([1. , 1. , 1. , 0.7, 0.9, 1. , 1. , 0.9, 1. , 0.9])

In [59]:
y_pred = cross_val_predict(clf, X_test, y_test, cv=10)

In [60]:
y_pred

array([1, 0, 2, 1, 2, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [61]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.96

In [33]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='micro')

0.96

In [32]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred, average='micro')

0.96

In [1]:
from sklearn.neighbors import KNeighborsClassifier

In [62]:
neigh = KNeighborsClassifier(n_neighbors=3)

In [63]:
cross_val_score(neigh, X_train, y_train, cv=10)

array([1. , 1. , 1. , 0.6, 0.9, 1. , 1. , 1. , 1. , 0.9])

In [64]:
y_pred = cross_val_predict(clf, X_test, y_test, cv=10)

In [65]:
accuracy_score(y_test, y_pred)

0.96

In [68]:
from sklearn.cluster import KMeans

In [69]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(X_train)

C:\Users\lol10\anaconda3\envs\ML\lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\lol10\anaconda3\envs\ML\lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [70]:
y_pred = kmeans.predict(X_test)

In [71]:
accuracy_score(y_test, y_pred)

0.08

In [73]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
print(scaler.fit(data))
print(scaler.mean_)
print(scaler.transform(data))
print(scaler.transform([[2, 2]]))

StandardScaler()
[0.5 0.5]
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
[[3. 3.]]
